### ISSUE TITLE
Optimisation of Candooo's features in mobile devices

### ISSUE THREAD

**Issue by joy-dey** [SahinAkhtargit/candooo#3]
The mobile version of candooo's feature list should be aligned to start rather than aligned to end
![image](https://github.com/SahinAkhtargit/candooo/assets/36854712/daff9c94-fc1c-44ac-a503-e43b54af2f0e)

**Comment by SahinAkhtargit** [comment]
Resolved

**Comment by joy-dey** [comment]
The issue has not been resolved. The first three points still appears RTL instead of LTR

**Comment by SahinAkhtargit** [comment]
Issue was Resolved
